export declare const GNSS_DEGREES_PRECISION_NUMBER_OF_DECIMAL_PLACES = 7;
export declare const ALTITUDE_PRECISION_NUMBER_OF_DECIMAL_PLACES = 2;
export declare const DISTANCE_PRECISION_NUMBER_OF_DECIMAL_PLACES = 1;
export declare const SPEED_PRECISION_NUMBER_OF_DECIMAL_PLACES = 2;
export declare const HEART_RATE_PRECISION_NUMBER_OF_DECIMAL_PLACES = 1;
export declare const CADENCE_PRECISION_NUMBER_OF_DECIMAL_PLACES = 1;
export declare const POWER_PRECISION_NUMBER_OF_DECIMAL_PLACES = 1;
export declare const TEMPERATURE_PRECISION_NUMBER_OF_DECIMAL_PLACES = 2;
